### PR TITLE
[Feature] Post flush events

### PR DESCRIPTION
**Pull request by javabudd**
While using this library I have come across several use cases/issues where a post flush event would have been very useful. One of the issues specifically was a race condition while queuing up jobs after the POST event, where the job could potentially be ran before the entity was flushed.

Since the event does not exist I've been altering the resource to perform the logic after the parent method has been called, which is not ideal. I think using the existing event system here could solve these issues and make integrations more consistent.

### CODE REVIEW

**Comment by TomHAnderson** [comment]
Doctrine already has a post flush event: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html

Can you provide a scenario where the Doctrine event is not enough?  By creating these new _flush events you are modeling the DoctrineResource on the ORM which is not how the event system works currently.  I've always used DoctrineResource events and Doctrine events for different purposes.  Adding the _flush events is almost-but-not-quite duplicating event positions (within the call lifecycle)

**Comment by javabudd** [comment]
The doctrine events are definitely a way to get it done but it doesn't feel right to me. For my use case I would only want this logic executing after an API request has been made. There are several areas in my codebase where entities can be modified outside of API calls (worker processes), and I would never want this logic executing there. I could wrap the logic around changeset conditionals but again, it just doesn't seem right. 🤷‍♂

**Comment by javabudd** [comment]
Scenario:

Entity is patched and a field is changed. A listener on POST detects the field change and modifies some entity information that is critical for a worker process. It then queues up a job to grab this critical information and processes it. Since there is no event to listen to after flush(), it is possible that the worker process will be ran before flush() occurs, causing a race condition.

**Comment by TomHAnderson** [comment]
Your scenario is missing a transaction.  Doctrine makes putting multiple queries into the same transaction.

Using the existing POST event add the worker process entity into the current transaction and do not flush() in your code.  Instead you know there will be a flush() after the event is done firing and your future work will be part of that same transaction.

**Pull request closed without merging**
