### PR TITLE
Fix for zfcampus/zf-oauth2#93 oAuth2 resource returns closure

### PR DESCRIPTION
**Pull request by TomHAnderson**
Addressed in #172

### CODE REVIEW

**Comment by akaraznevic** [comment]
:+1:

**Comment by weierophinney** [comment]
There's a potential problem with this, as it assumes that you are using per-application OAuth2 authentication vs per-API (as introduced in 1.1.0). Ideally, the server instance should be pulled using the "oauth" route parameter, or using the zf-mvc-auth adapter mapped by the matched controller service.

Honestly, I think this aspect needs to be audited a bit more closely; I'm not entirely sure why the query filter needs the OAuth2\Server instance. @TomHAnderson, can you explain what it does?

**Comment by TomHAnderson** [comment]
The OAuth2 server is used in zf-apigility-doctrine to validate an OAuth2 request:
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Query/Provider/AbstractQueryProvider.php#L117

This is the only reason OAuth2 is in the query & create providers.  This is intended to be used as described here in the last section, Securing Resources with zf-apigility-doctrine
 
https://github.com/TomHAnderson/zf-oauth2-doctrine-orm/blob/852f954a5381cc5cc4cc4eb557cb9c9a0cf80d86/README.md

I removed this text just the other day.  Perhaps the OAuth2 code should be removed from zf-apigility-doctrine and a doc should be written to describe how to create the function?  I think re-architecting this would be ok.

**Comment by weierophinney** [comment]
@TomHAnderson The problem is that zf-mvc-auth provides an override factory for the `ZF\OAuth2\Service\OAuth2Server` service, which accepts an optional argument, the oauth2 adapter as defined in the zf-mvc-auth adapters configuration. The adapter name is pulled at run time from a route parameter, when first authenticating against the server, or based on the Authorization header and/or controller name on subsequent runs (when providing the token). As such, pulling the value inside a service factory is problematic.

I think the better course would be to create documentation on how to create the functionality when needed by an application.

**Pull request merged**
